package com.crm.backend.integration;

public enum IntegrationAuditAction {
    INTEGRATION_CREATED,
    INTEGRATION_UPDATED,
    INTEGRATION_CREDENTIALS_UPDATED,
    INTEGRATION_VERIFIED,
    INTEGRATION_VERIFICATION_FAILED,
    INTEGRATION_DISABLED,
    INTEGRATION_REVOKED,
    INTEGRATION_DELIVERY_QUEUED,
    INTEGRATION_DELIVERY_SUCCEEDED,
    INTEGRATION_DELIVERY_FAILED,
    INTEGRATION_DELIVERY_RETRIED,
    INTEGRATION_DELIVERY_CANCELLED
}
