package com.crm.backend.workflow;

public enum WorkflowAuditAction {
    WORKFLOW_CREATED,
    WORKFLOW_UPDATED,
    WORKFLOW_ACTIVATED,
    WORKFLOW_PAUSED,
    WORKFLOW_ARCHIVED,
    WORKFLOW_EXECUTION_RETRIED,
    WORKFLOW_EXECUTION_CANCELLED,
    WORKFLOW_EXECUTION_EXHAUSTED
}
