package com.crm.backend.subscription;

public enum SubscriptionAuditAction {
    SUBSCRIPTION_TRIAL_STARTED,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_PLAN_CHANGED,
    SUBSCRIPTION_GRACE_PERIOD_STARTED,
    SUBSCRIPTION_CANCELLATION_SCHEDULED,
    SUBSCRIPTION_CANCELED,
    SUBSCRIPTION_EXPIRED,
    BILLING_CUSTOMER_CREATED,
    BILLING_CHECKOUT_CREATED,
    BILLING_PORTAL_OPENED,
    BILLING_WEBHOOK_PROCESSED,
    SUBSCRIPTION_PROVIDER_SYNCED
}
