package com.crm.backend.subscription;

public enum SubscriptionAuditAction {
    SUBSCRIPTION_TRIAL_STARTED,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_PLAN_CHANGED,
    SUBSCRIPTION_GRACE_PERIOD_STARTED,
    SUBSCRIPTION_CANCELLATION_SCHEDULED,
    SUBSCRIPTION_CANCELED,
    SUBSCRIPTION_EXPIRED
}
