package com.crm.backend.webhook;

public enum WebhookAuditAction {
    WEBHOOK_SUBSCRIPTION_CREATED,
    WEBHOOK_SUBSCRIPTION_UPDATED,
    WEBHOOK_SUBSCRIPTION_ENABLED,
    WEBHOOK_SUBSCRIPTION_DISABLED,
    WEBHOOK_SECRET_ROTATED,
    WEBHOOK_SUBSCRIPTION_REVOKED,
    WEBHOOK_DELIVERY_EXHAUSTED,
    WEBHOOK_DELIVERY_REPLAYED
}
