package com.crm.backend.permission;

public enum PermissionName {

    USER_VIEW,
    USER_CREATE,
    USER_UPDATE,
    USER_DEACTIVATE,
    USER_ROLE_CHANGE,

    CUSTOMER_VIEW,
    CUSTOMER_CREATE,
    CUSTOMER_UPDATE,
    CUSTOMER_ARCHIVE,

    LEAD_VIEW,
    LEAD_CREATE,
    LEAD_UPDATE,
    LEAD_CONVERT,
    LEAD_ARCHIVE,

    CONTACT_VIEW,
    CONTACT_CREATE,
    CONTACT_UPDATE,
    CONTACT_ARCHIVE,

    TASK_VIEW,
    TASK_CREATE,
    TASK_UPDATE,
    TASK_ASSIGN,
    TASK_COMPLETE,

    NOTE_VIEW,
    NOTE_CREATE,
    NOTE_UPDATE,

    DASHBOARD_VIEW,
    REPORT_VIEW,
    REPORT_EXPORT,
    AUDIT_LOG_VIEW,
    PERMISSION_MANAGE
}